[package]
name = "oasis-runtime-sdk-contracts"
description = "Smart contracts module for the Oasis Runtime SDK."
version = "0.1.0"
authors = ["Oasis Protocol Foundation <info@oasisprotocol.org>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
cbor = { version = "0.1.7", package = "oasis-cbor" }
oasis-contract-sdk-types = { path = "../../../contract-sdk/types", features = ["oasis-runtime-sdk"] }
oasis-runtime-sdk = { path = "../.." }

# Internal Wasm3 bindings.
wasm3 = { git = "https://github.com/oasisprotocol/wasm3-rs", tag = "v0.2.0" }

# Third party.
anyhow = "1.0"
blake3 = { version = "1.0.0", features = ["traits-preview"] }
num-traits = "0.2.14"
thiserror = "1.0"
walrus = "0.19.0"

[dev-dependencies]
wat = "1.0"
