name: Determine Branch Tag
description: Determine the tag to be used for e.g. building Docker images
inputs:
  dir:
    description: The root directory for the sources to inspect
    default: ${{ github.workspace }}
    required: false
  use_base_for_pr:
    description: Should the base branch be used for pull requests
    default: no
    required: false
  trim_prefix:
    description: Trim the given prefix
    default: no
    required: false
outputs:
  tag:
    description: The tag derived from the branch information
    value: ${{ steps.determine-tag.outputs.tag }}
  created:
    description: The timestamp for when the tag was created
    value: ${{ steps.determine-tag.outputs.created }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: determine-tag
      run: |
        if [[ -z $GITHUB_BASE_REF ]]; then
          # On master/stable branches or tags.
          branch=${GITHUB_REF_NAME}

          if [[ -n "${{ inputs.trim_prefix }}" ]]; then
            branch=${branch#"${{ inputs.trim_prefix }}"}
          fi
        elif [[ "${{ inputs.use_base_for_pr }}" == "yes" ]]; then
          # Use base branch.
          branch=$GITHUB_BASE_REF
        else
          # On pull request branches.
          branch=pr-$(git describe --always --match '' --abbrev=7)
        fi
        branch=${branch//\//-}
        echo "tag=$(echo ${branch})" >> $GITHUB_OUTPUT
        echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
