version: 2
updates:

  # Manage Github Actions versions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "ci:"
    labels:
      - c:deps
      - c:testing

  # Manage client-sdk/go package versions.
  - package-ecosystem: gomod
    directory: client-sdk/go/
    schedule:
      interval: daily
    commit-message:
      prefix: "client-sdk/go:"
    labels:
      - c:deps
      - c:client-sdk/go
    ignore:
      # oasis-core is manually kept up to date.
      - dependency-name: github.com/oasisprotocol/oasis-core/go

  # Manage tests/e2e package versions.
  - package-ecosystem: gomod
    directory: tests/e2e
    schedule:
      interval: daily
    commit-message:
      prefix: "tests/e2e:"
    labels:
      - c:deps
      - c:testing
    ignore:
      # oasis-core is manually kept up to date.
      - dependency-name: github.com/oasisprotocol/oasis-core/go
      # client-sdk is replaced with the local up-to-date version.
      - dependency-name: github.com/oasisprotocol/oasis-sdk/client-sdk/go

  # Manage Rust package versions.
  - package-ecosystem: cargo
    directories:
      - /
      # Contract SDK specs.
      - contract-sdk/specs/token/oas20/
      - contract-sdk/specs/access/oas173/
      # Test contracts.
      - tests/contracts/hello/
      - tests/contracts/bench/
    schedule:
      interval: daily
    commit-message:
      prefix: "runtime-sdk:"
    groups:
      # Update all other dependencies in a single PR.
      rust:
        # Update all dependencies, unless explicitly ignored.
        patterns:
          - "*"
        # Excluded dependencies are updated in separate PRs.
        # Commented out because it requires at least one entry to be valid.
        # exclude-patterns: []
    # Ignored depenednecies are ignored by dependabot.
    ignore:
      # oasis-core dependencies are manually kept up to date.
      - dependency-name: oasis-core-runtime
      - dependency-name: oasis-core-keymanager
    labels:
      - c:deps
      - rust
    labels:
      - c:deps
      - c:runtime-sdk

  # Manage npm package versions.
  - package-ecosystem: npm
    directory: client-sdk/ts-web
    schedule:
      interval: daily
    commit-message:
      prefix: "client/ts-web:"
    labels:
      - c:deps
      - c:client-sdk/typescript

  # Manage client-sdk/ts-web/core/reflect-go package versions.
  - package-ecosystem: gomod
    directory: client-sdk/ts-web/core/reflect-go/
    schedule:
      interval: daily
    commit-message:
      prefix: "client/reflect:"
    labels:
      - c:deps
      - c:client-sdk/go
    ignore:
      # oasis-core is manually kept up to date.
      - dependency-name: github.com/oasisprotocol/oasis-core/go
