[workspace]
members = [
    "runtime-sdk",
    "runtime-sdk-macros",

    # Test runtimes.
    "tests/runtimes/simple-keyvalue",
    "tests/runtimes/simple-consensus",
]

[patch.crates-io]
# TODO: Remove when merged upstream (briansmith/ring#738).
ring = { git = "https://github.com/oasislabs/ring-sgx", branch = "sgx-target" }
