[workspace]
members = [
    "runtime-sdk",
    "runtime-sdk-macros",

    "client-sdk/rust",

    # Test runtimes.
    "tests/runtimes/benchmarking",
    "tests/runtimes/simple-keyvalue",
    "tests/runtimes/simple-consensus",
]
