name: Determine Rust Toolchain Version
description: Determine the required rust toolchain version
outputs:
  version:
    description: The version detected
    value: ${{ steps.version.outputs.version }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: version
      run: |
        echo "version=$(sed -E -n 's/channel.+=.+\"nightly-(.+)\"/\1/p' < rust-toolchain.toml)" >> $GITHUB_OUTPUT
