name: Unit Test Rust Worskapce with Coverage
description: Run unit tests on a Rust workspace with coverage and uploads results to codecov
inputs:
  manifest_path:
    description: Path to the Cargo.toml manifest of the Rust sources to build and test
    default: ${{ github.workspace }}/Cargo.toml
    required: false
runs:
  using: composite
  steps:
    - name: Unit tests with coverage
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.20.1'
        args: '--avoid-cfg-tarpaulin --manifest-path ${{ inputs.manifest_path }} -- --test-threads 1'
      env:
        # Required as tarpaulin doesn't honor .cargo/config.
        RUSTFLAGS: -C target-feature=+aes,+ssse3

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v2.1.0

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2.2.4
      with:
        name: code-coverage-report
        path: cobertura.xml
