[package]
name = "oasis-runtime-sdk-evm"
description = "EVM module for the Oasis Runtime SDK."
version = "0.1.0"
authors = ["Oasis Protocol Foundation <info@oasisprotocol.org>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
cbor = { version = "0.1.8", package = "oasis-cbor" }
oasis-runtime-sdk = { path = "../.." }

# Third party.
anyhow = "1.0"
blake3 = { version = "1.0.0", features = ["traits-preview"] }
once_cell = "1.8.0"
thiserror = "1.0"

# Ethereum.
evm = "0.30.1"
fixed-hash = "0.7.0"
primitive-types = { version = "0.10.1", default-features = false, features = ["rlp", "num-traits"] }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
uint = "0.9.1"

