name: release-rofl-scheduler

on:
  push:
    tags:
      - "rofl-scheduler/v[0-9]+.[0-9]+*"

permissions:
  contents: write

jobs:
  release-rofl-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Oasis CLI
        env:
          CLI_VERSION: 0.13.4
        run: |
          wget https://github.com/oasisprotocol/cli/releases/download/v${CLI_VERSION}/oasis_cli_${CLI_VERSION}_linux_amd64.tar.gz -O cli.tar.gz
          tar --strip-components 1 -xf cli.tar.gz

      - name: Build rofl-scheduler for Testnet
        working-directory: rofl-scheduler
        run: ../oasis rofl build --deployment testnet --offline --verify

      - name: Build rofl-scheduler for Mainnet
        working-directory: rofl-scheduler
        run: ../oasis rofl build --deployment mainnet --offline --verify

      - name: Publish the release
        uses: ncipollo/release-action@v1
        with:
          artifacts: rofl-scheduler/rofl-scheduler.testnet.orc,rofl-scheduler/rofl-scheduler.mainnet.orc
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
